import Head from "next/head";
import Sanity from "../sanityClient";
import PostList from "../components/PostList";

const Home = ({ developerLogs, tipsAndTricks }: any) => {
  return (
    <div>
      <Head>
        <title>nemil.io Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Tips &amp; Tricks</h2>
      <PostList posts={tipsAndTricks} />
      <h2>Developer logs</h2>
      <PostList posts={developerLogs} />
    </div>
  );
};

export async function getServerSideProps() {
  const developerLogs =
    await Sanity.fetch(`*[_type == "post" && "Developer Log" in categories[]->title] | order(_createdAt desc) {
    ...,
    author -> {
      name,
      image { asset -> {
          url
        }
      }
    },
    mainImage {asset -> {
      url
      }
    }
  }`);
  const tipsAndTricks =
    await Sanity.fetch(`*[_type == "post" && "Tips & Tricks" in categories[]->title] | order(_createdAt desc) {
    ...,
    author -> {
      name,
      image { asset -> {
          url
        }
      }
    },
    mainImage {asset -> {
      url
      }
    }
  }`);
  return {
    props: { developerLogs, tipsAndTricks },
  };
}

export default Home;
