import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Sanity, { urlFor } from "../sanityClient";
import { formatDistanceToNowStrict } from "date-fns";
import Link from "next/link";

type Props = {
  posts: any;
};

const Home = ({ posts }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>nemil.io Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Projects</h2>

      <h2>Developer log</h2>
      <ul className={styles["post-list"]}>
        {posts.map((post: any) => (
          <Link key={post._id} href={`/post/${post._id}`}>
            <a className={styles.post}>
              <div className={styles["post-image"]}>
                <img src={post.mainImage && post.mainImage.asset.url} alt="" />
              </div>
              <h3>{post.title}</h3>
              <div className={styles.info}>
                <div>
                  <p>by {post.author.name}</p>
                  <span>
                    Posted{" "}
                    {formatDistanceToNowStrict(new Date(post.publishedAt), {
                      addSuffix: true,
                    })}
                  </span>
                </div>
                <img src={post.author.image.asset.url} alt="" />
              </div>
            </a>
          </Link>
        ))}
      </ul>
    </div>
  );
};

export async function getServerSideProps() {
  const posts = await Sanity.fetch(`*[_type == "post"]{
    _id,
    title,
    body,
    publishedAt,
    author -> {
  name,
  image{asset -> {
  url
}}
},
    mainImage{asset -> {
      url
    }}
  }`);
  return {
    props: { posts },
  };
}

export default Home;
